repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        args: [--settings-path, ./pyproject.toml]

  -   repo: https://github.com/ambv/black
      rev: 20.8b1
      hooks:
        - id: black

  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.8.4
      hooks:
        - id: flake8